title: Out of Bounds
description: KOK 개발 블로그

url: http://kimsungyoon-kok.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: Project
    url: /project
  - title: Algorithm
    url: /categories
  - title: About
    url: /about
  - title: 개인정보처리방침
    url: /private
  

social:
  github: https://github.com/KimSungYoon-KOK
  twitter: 
  facebook: 
  email: sungyun1997@gmail.com

google_analytics: "UA-58263416-1"
